Hackathon team487twh wokier trycatch
green-code-initiative/ecoCode-common pull request #15
Opened 2023-04-06 10:48 UTC by wokier

- Added label 'eco-design' on java:S1696 'Avoid catching NullPointerException.'
- Improved documentation on tag install tooling

2023-04-10 20:01 UTC, dedece35 commented
Hi @wokier,

first of all, thank you for your PR.

unfortunately, there is already an existing PR about the same subject : #18 

this is a PR that purpose is to refactor this tagging system to make it more automatic : start from a markdown file to put tags to native SonarQube rules.
it's a real improvement of this system and I think this is the first thing that we have to integrate before other things.

Sorry but I'm reviewing this PR #18.
Next you could check if your PR is still relevant or not.

2023-04-10 21:16 UTC, dedece35 requested changes
as explained, we are waiting for #17 to integrate your modifications

2023-04-10 21:16 UTC, dedece35 commented on tools/rules_config/README.md
> +3. launch `install_tag.sh` to add custom tag to your rules (change SIMULATION=0 in configration to do real calls)
typo error

2023-04-10 21:16 UTC, dedece35 commented on tools/rules_config/_config.sh
> +RULES_KEYS=css:S4655,php:S2014,Web:ItemTagNotWithinContainerTagCheck,java:S1696
please keep only your rule `java:S1696` (other rules are only for testing the system

2023-04-11 08:05 UTC, dedece35 commented
Hi @wokier,

PR #17 has just been merged.
Could you resolve your conflicts regarding that now rules list is inside a new file named `SONAR_RULES_REUSED.md` in which you must write your rule and an explanation about this inclusion : please check the content of this new file

2024-11-18 13:37 UTC, dedece35 commented
Hi @wokier,
any news about this PR ?
(can you correct the conflicts please)

2024-11-22 15:45 UTC, wokier commented
Here it is

2025-05-13 20:29 UTC, dedece35 commented
Hi @wokier,
sorry but you don't answer to my previous question ... why do we have to add this rule with the tag "creedengo" ?
thank you.

2025-05-19 10:21 UTC, wokier commented
Hi

Here is a benchmark that demonstrates that catching exceptions is less performant in Java than testing null.
https://github.com/wokier/green-code-initiative-trycatch-benchmark

2026-07-04 22:16 UTC, merged

2026-07-04 22:17 UTC, dedece35 commented
Hi @wokier, thank you for contribution.